services:
  api-gateway:
    image: 'mouralucas/rolf-services:gateway'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka_host_name=$eureka_host_name

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - "api-gateway"
    environment:
      - server_host=$server_host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"